use aed_project;

select * from admins;
select * from csr;
select * from customer;
select * from delivery_agent;
select * from farms;
select * from shipping_agent;
select * from ssr;
select * from store;
select * from store_manager;
select * from supplier;
select * from warehouse;
select * from warehouse_manager;
select * from store_items;
select * from warehouse_orders;
select * from user_orders;
select * from shipment_orders;
select * from supplier_orders;
select * from cart;
select * from delivery_orders;