/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;
import Model.UserDirectory;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;

/**
 *
 * @author mahith
 */
public class signupPanel extends javax.swing.JPanel {

    /**
     * Creates new form signupPanel
     */
    Connection connection;
    UserDirectory userdir;
    public signupPanel(Connection connection,UserDirectory userdir) {
        initComponents();
        this.connection=connection;
        this.userdir=userdir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerHeading = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        lblUserMobile = new javax.swing.JLabel();
        lblUserGender = new javax.swing.JLabel();
        lblUserUserName = new javax.swing.JLabel();
        lblUserPassword = new javax.swing.JLabel();
        pwdUserPassword = new javax.swing.JPasswordField();
        txtUserUserName = new javax.swing.JTextField();
        cbUserGender = new javax.swing.JComboBox<>();
        txtUserMobile = new javax.swing.JTextField();
        txtUserEmail = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnCreateUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(25, 54, 82));

        lblCustomerHeading.setBackground(new java.awt.Color(25, 54, 82));
        lblCustomerHeading.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblCustomerHeading.setForeground(new java.awt.Color(204, 204, 204));
        lblCustomerHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerHeading.setText("Create a New User");

        lblUserName.setBackground(new java.awt.Color(25, 54, 82));
        lblUserName.setForeground(new java.awt.Color(204, 204, 204));
        lblUserName.setText("Name :");

        lblUserEmail.setBackground(new java.awt.Color(25, 54, 82));
        lblUserEmail.setForeground(new java.awt.Color(204, 204, 204));
        lblUserEmail.setText("Email :");

        lblUserMobile.setBackground(new java.awt.Color(25, 54, 82));
        lblUserMobile.setForeground(new java.awt.Color(204, 204, 204));
        lblUserMobile.setText("Mobile :");

        lblUserGender.setBackground(new java.awt.Color(25, 54, 82));
        lblUserGender.setForeground(new java.awt.Color(204, 204, 204));
        lblUserGender.setText("Gender :");

        lblUserUserName.setBackground(new java.awt.Color(25, 54, 82));
        lblUserUserName.setForeground(new java.awt.Color(204, 204, 204));
        lblUserUserName.setText("User Name :");

        lblUserPassword.setBackground(new java.awt.Color(25, 54, 82));
        lblUserPassword.setForeground(new java.awt.Color(204, 204, 204));
        lblUserPassword.setText("Password :");

        pwdUserPassword.setBackground(new java.awt.Color(25, 54, 82));
        pwdUserPassword.setForeground(new java.awt.Color(204, 204, 204));

        txtUserUserName.setBackground(new java.awt.Color(25, 54, 82));
        txtUserUserName.setForeground(new java.awt.Color(204, 204, 204));

        cbUserGender.setBackground(new java.awt.Color(25, 54, 82));
        cbUserGender.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbUserGender.setForeground(new java.awt.Color(204, 204, 204));
        cbUserGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Male", "Female", "Other", "Do not want to disclose", " " }));

        txtUserMobile.setBackground(new java.awt.Color(25, 54, 82));
        txtUserMobile.setForeground(new java.awt.Color(204, 204, 204));

        txtUserEmail.setBackground(new java.awt.Color(25, 54, 82));
        txtUserEmail.setForeground(new java.awt.Color(204, 204, 204));

        txtUserName.setBackground(new java.awt.Color(25, 54, 82));
        txtUserName.setForeground(new java.awt.Color(204, 204, 204));

        btnCreateUser.setBackground(new java.awt.Color(25, 54, 82));
        btnCreateUser.setForeground(new java.awt.Color(204, 204, 204));
        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUserUserName)
                            .addComponent(lblUserPassword)
                            .addComponent(lblUserGender)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustomerHeading)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserName)
                                    .addComponent(lblUserEmail)
                                    .addComponent(lblUserMobile))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUserMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pwdUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUserGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(btnCreateUser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblCustomerHeading)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserEmail)
                    .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserMobile)
                    .addComponent(txtUserMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserUserName)
                    .addComponent(txtUserUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPassword)
                    .addComponent(pwdUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserGender)
                    .addComponent(cbUserGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(btnCreateUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        public boolean customerValidation(){
    ArrayList msg=null;
    msg= new ArrayList();
    
  
        if(txtUserName.getText().isBlank()|| !(txtUserName.getText().matches("^[a-zA-Z ]*$")))
        {msg.add("Please enter the Customer Name without special characters and do not leave it blank");} 
        if( txtUserEmail.getText().isBlank()||!( txtUserEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$")))
        msg.add(("Please enter the correct email (xxx@xx.xx)"));
        if(!(String.valueOf(txtUserMobile.getText()).matches("^[0-9]{10}$")))
       {msg.add("Please enter the 10 digit mobile number");}
       if(txtUserUserName.getText().isBlank()|| !(txtUserUserName.getText().matches("^[0-9a-zA-Z@._]*$")))
        {msg.add("Please enter the User name but do not leave it blank. Use only digts,lower & upper alphabets,special characters(@,.,_)");}
       if(String.valueOf(pwdUserPassword.getPassword()).isBlank())
        msg.add("Password field is empty");
        if(String.valueOf(cbUserGender.getSelectedItem()).isBlank())
        {msg.add("Please select Gender");}    
        
        if(!(msg.isEmpty()))
        {JOptionPane.showMessageDialog(this, msg.toArray());
        msg.clear();
        return false;}
        else 
        return true; 
    }
    
    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
           String name =txtUserName.getText();
      String email = txtUserEmail.getText();
      String mobile = txtUserMobile.getText();
      String username = txtUserUserName.getText();
      String password = String.valueOf(pwdUserPassword.getPassword());
      String gender = cbUserGender.getSelectedItem().toString();
  
     if(customerValidation()){
      if(userdir.addCustomer(name, email, username, mobile, password, gender))
          
      JOptionPane.showMessageDialog(this, "Customer Successfully Created..!!");
      txtUserName.setText("");
      txtUserEmail.setText("");
      txtUserMobile.setText("");
      txtUserName.setText("");
      pwdUserPassword.setText("");
     }
     else{
           JOptionPane.showMessageDialog(this, "Customer Not Created..!!");
     }

    }//GEN-LAST:event_btnCreateUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox<String> cbUserGender;
    private javax.swing.JLabel lblCustomerHeading;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserGender;
    private javax.swing.JLabel lblUserMobile;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPassword;
    private javax.swing.JLabel lblUserUserName;
    private javax.swing.JPasswordField pwdUserPassword;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserMobile;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserUserName;
    // End of variables declaration//GEN-END:variables
}
