/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.customer;

import java.awt.CardLayout;
import java.sql.*;
/**
 *
 * @author mahith
 */
public class CustomerHomePanel extends javax.swing.JPanel {
    Connection connection;
    /**
     * Creates new form CustomerHomePanel
     */
    public CustomerHomePanel(Connection connection) {
        this.connection= connection;
        initComponents();
        
        CustomerPanel panel = new CustomerPanel(connection);
        rightCustomerPanel.add("workArea", panel);
        CardLayout layout = (CardLayout) rightCustomerPanel.getLayout();
        layout.next(rightCustomerPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        homeCustomerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        customerChatBoxLabel = new javax.swing.JLabel();
        customerOrdersPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        customerOrdersLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rightCustomerPanel = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(215, 81, 81));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 840));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 840));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeCustomerPanel.setBackground(new java.awt.Color(215, 81, 81));
        homeCustomerPanel.setToolTipText("");
        homeCustomerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeCustomerPanelMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(215, 81, 81));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Home Page.png"))); // NOI18N
        jLabel2.setToolTipText("");

        customerChatBoxLabel.setBackground(new java.awt.Color(215, 81, 81));
        customerChatBoxLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        customerChatBoxLabel.setText("Home");

        javax.swing.GroupLayout homeCustomerPanelLayout = new javax.swing.GroupLayout(homeCustomerPanel);
        homeCustomerPanel.setLayout(homeCustomerPanelLayout);
        homeCustomerPanelLayout.setHorizontalGroup(
            homeCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerChatBoxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        homeCustomerPanelLayout.setVerticalGroup(
            homeCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerChatBoxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(homeCustomerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 50));

        customerOrdersPanel.setBackground(new java.awt.Color(215, 81, 81));
        customerOrdersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customerOrdersPanelMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(215, 81, 81));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Business.png"))); // NOI18N

        customerOrdersLabel.setBackground(new java.awt.Color(215, 81, 81));
        customerOrdersLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        customerOrdersLabel.setText("Manage Orders");
        customerOrdersLabel.setPreferredSize(new java.awt.Dimension(115, 16));

        javax.swing.GroupLayout customerOrdersPanelLayout = new javax.swing.GroupLayout(customerOrdersPanel);
        customerOrdersPanel.setLayout(customerOrdersPanelLayout);
        customerOrdersPanelLayout.setHorizontalGroup(
            customerOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerOrdersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        customerOrdersPanelLayout.setVerticalGroup(
            customerOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerOrdersPanelLayout.createSequentialGroup()
                        .addComponent(customerOrdersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.add(customerOrdersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 280, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 100));

        jLabel1.setBackground(new java.awt.Color(215, 81, 81));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Customer Landing Page");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 10));

        rightCustomerPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightCustomerPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        rightCustomerPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeCustomerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeCustomerPanelMousePressed
        // TODO add your handling code here:
        CustomerPanel panel = new CustomerPanel(connection);
        rightCustomerPanel.add("workArea", panel);
        CardLayout layout = (CardLayout) rightCustomerPanel.getLayout();
        layout.next(rightCustomerPanel);
    }//GEN-LAST:event_homeCustomerPanelMousePressed

    private void customerOrdersPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerOrdersPanelMousePressed
        customerOrdersPanel orders = new customerOrdersPanel(connection);
        rightCustomerPanel.add("Customer orders",orders );
        CardLayout layout = (CardLayout) rightCustomerPanel.getLayout();
        layout.next(rightCustomerPanel);
    }//GEN-LAST:event_customerOrdersPanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerChatBoxLabel;
    private javax.swing.JLabel customerOrdersLabel;
    private javax.swing.JPanel customerOrdersPanel;
    private javax.swing.JPanel homeCustomerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel rightCustomerPanel;
    // End of variables declaration//GEN-END:variables

    
}
