/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.StoreManager;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.*;

/**
 *
 * @author mohit
 */
public class StoreManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StoreManagerJPanel
     */
    Connection connection;
    String managerName;
    public StoreManagerJPanel(Connection connection, String managerName) {
        initComponents();
        storeGraphs(connection);
        this.connection=connection;
        this.managerName = managerName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        manageStorePanel = new javax.swing.JPanel();
        manageStoreLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manageUserOrdersPanel = new javax.swing.JPanel();
        manageUserOrdersLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        manageWarehouseOrdersPanel = new javax.swing.JPanel();
        manageWarehouseOrdersLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        homePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        rightStoreAdminPanel = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(227, 73, 78));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 840));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 840));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageStorePanel.setBackground(new java.awt.Color(227, 73, 78));
        manageStorePanel.setToolTipText("");
        manageStorePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageStorePanelMousePressed(evt);
            }
        });

        manageStoreLabel.setBackground(new java.awt.Color(25, 56, 82));
        manageStoreLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        manageStoreLabel.setText("Manage Store");
        manageStoreLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageStoreLabelMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(215, 81, 81));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Online Store.png"))); // NOI18N
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout manageStorePanelLayout = new javax.swing.GroupLayout(manageStorePanel);
        manageStorePanel.setLayout(manageStorePanelLayout);
        manageStorePanelLayout.setHorizontalGroup(
            manageStorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageStorePanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageStoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageStorePanelLayout.setVerticalGroup(
            manageStorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageStorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageStorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageStoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(manageStorePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 50));

        manageUserOrdersPanel.setBackground(new java.awt.Color(227, 73, 78));
        manageUserOrdersPanel.setToolTipText("");
        manageUserOrdersPanel.setPreferredSize(new java.awt.Dimension(264, 48));
        manageUserOrdersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageUserOrdersPanelMousePressed(evt);
            }
        });

        manageUserOrdersLabel.setBackground(new java.awt.Color(25, 56, 82));
        manageUserOrdersLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manageUserOrdersLabel.setText("Manage User Orders");
        manageUserOrdersLabel.setAutoscrolls(true);
        manageUserOrdersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageUserOrdersLabelMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(25, 56, 82));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User.png"))); // NOI18N

        javax.swing.GroupLayout manageUserOrdersPanelLayout = new javax.swing.GroupLayout(manageUserOrdersPanel);
        manageUserOrdersPanel.setLayout(manageUserOrdersPanelLayout);
        manageUserOrdersPanelLayout.setHorizontalGroup(
            manageUserOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserOrdersPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageUserOrdersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageUserOrdersPanelLayout.setVerticalGroup(
            manageUserOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageUserOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(manageUserOrdersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(manageUserOrdersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 280, 60));

        manageWarehouseOrdersPanel.setBackground(new java.awt.Color(227, 73, 78));
        manageWarehouseOrdersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageWarehouseOrdersPanelMousePressed(evt);
            }
        });

        manageWarehouseOrdersLabel.setBackground(new java.awt.Color(215, 81, 81));
        manageWarehouseOrdersLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manageWarehouseOrdersLabel.setText("Manage Warehouse Orders");
        manageWarehouseOrdersLabel.setPreferredSize(new java.awt.Dimension(115, 16));

        jLabel6.setBackground(new java.awt.Color(215, 81, 81));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Supply Chain.png"))); // NOI18N

        javax.swing.GroupLayout manageWarehouseOrdersPanelLayout = new javax.swing.GroupLayout(manageWarehouseOrdersPanel);
        manageWarehouseOrdersPanel.setLayout(manageWarehouseOrdersPanelLayout);
        manageWarehouseOrdersPanelLayout.setHorizontalGroup(
            manageWarehouseOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageWarehouseOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageWarehouseOrdersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        manageWarehouseOrdersPanelLayout.setVerticalGroup(
            manageWarehouseOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageWarehouseOrdersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(manageWarehouseOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(manageWarehouseOrdersPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(manageWarehouseOrdersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        jPanel3.add(manageWarehouseOrdersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 70));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 280, 50));

        jLabel1.setBackground(new java.awt.Color(215, 81, 81));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("STORE MANAGEMENT SYSTEM");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 10));

        homePanel.setBackground(new java.awt.Color(227, 73, 78));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homePanelMousePressed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Home Page.png"))); // NOI18N

        home.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, -1));

        rightStoreAdminPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightStoreAdminPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        rightStoreAdminPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightStoreAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightStoreAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageStoreLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStoreLabelMousePressed
        manageStore();
    }//GEN-LAST:event_manageStoreLabelMousePressed

    private void manageStorePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStorePanelMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_manageStorePanelMousePressed

    private void manageUserOrdersLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserOrdersLabelMousePressed
        manageUserOrders();        
    }//GEN-LAST:event_manageUserOrdersLabelMousePressed

    private void manageUserOrdersPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserOrdersPanelMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_manageUserOrdersPanelMousePressed

    private void manageWarehouseOrdersPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageWarehouseOrdersPanelMousePressed
       manageWarehouseOrders();
    }//GEN-LAST:event_manageWarehouseOrdersPanelMousePressed

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        storeGraphs(connection);
    }//GEN-LAST:event_homeMousePressed

    private void homePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMousePressed
        // TODO add your handling code here:
        storeGraphs(connection);
    }//GEN-LAST:event_homePanelMousePressed

    private void manageStore(){
        homePanel.setBackground(new Color(227, 73, 78));
        manageStorePanel.setBackground(new Color(135, 206, 235));
        manageUserOrdersPanel.setBackground(new Color(227, 73, 78));
        manageWarehouseOrdersPanel.setBackground(new Color(227, 73, 78));
        ManageStoreJPanel manageStoreJPanel = new ManageStoreJPanel(connection, managerName);        
        rightStoreAdminPanel.add("manageStoreJPanel",manageStoreJPanel);
        CardLayout layout = (CardLayout) rightStoreAdminPanel.getLayout();
        layout.next(rightStoreAdminPanel);
    }
    
    private void manageUserOrders(){
        homePanel.setBackground(new Color(227, 73, 78));
        manageStorePanel.setBackground(new Color(227, 73, 78));
        manageUserOrdersPanel.setBackground(new Color(135, 206, 235));
        manageWarehouseOrdersPanel.setBackground(new Color(227, 73, 78));
        ManageUserOrdersJPanel manageUserOrdersJPanel = new ManageUserOrdersJPanel(connection);        
        rightStoreAdminPanel.add("manageUserOrdersJPanel",manageUserOrdersJPanel);
        CardLayout layout = (CardLayout) rightStoreAdminPanel.getLayout();
        layout.next(rightStoreAdminPanel);
    }
    
    private void manageWarehouseOrders(){
        homePanel.setBackground(new Color(227, 73, 78));
        manageStorePanel.setBackground(new Color(227, 73, 78));
        manageUserOrdersPanel.setBackground(new Color(227, 73, 78));
        manageWarehouseOrdersPanel.setBackground(new Color(135, 206, 235));
        ManageWarehouseOrdersJPanel manageSupplyOrdersJPanel = new ManageWarehouseOrdersJPanel(connection);        
        rightStoreAdminPanel.add("manageSupplyOrdersJPanel",manageSupplyOrdersJPanel);
        CardLayout layout = (CardLayout) rightStoreAdminPanel.getLayout();
        layout.next(rightStoreAdminPanel);
    }

    private void storeGraphs(Connection connection){
        homePanel.setBackground(new Color(135, 206, 235));
        manageStorePanel.setBackground(new Color(227, 73, 78));
        manageUserOrdersPanel.setBackground(new Color(227, 73, 78));
        manageWarehouseOrdersPanel.setBackground(new Color(227, 73, 78));
        ViewStoreGraphsJPanel viewStoreGraphsJPanel = new ViewStoreGraphsJPanel(connection);
        rightStoreAdminPanel.add("viewStoreGraphsJPanel",viewStoreGraphsJPanel);
        CardLayout layout = (CardLayout) rightStoreAdminPanel.getLayout();
        layout.next(rightStoreAdminPanel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel manageStoreLabel;
    private javax.swing.JPanel manageStorePanel;
    private javax.swing.JLabel manageUserOrdersLabel;
    private javax.swing.JPanel manageUserOrdersPanel;
    private javax.swing.JLabel manageWarehouseOrdersLabel;
    private javax.swing.JPanel manageWarehouseOrdersPanel;
    private javax.swing.JPanel rightStoreAdminPanel;
    // End of variables declaration//GEN-END:variables
}
