/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Delivery;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import userinterface.CustomerServiceRepresentative.csrPanel;
import userinterface.Maps.mapMarkerPanel;
import userinterface.Maps.mapsPanel;
import userinterface.customer.customerCart;

/**
 *
 * @author mahith
 */
public class deliveryAgentHome extends javax.swing.JPanel {
String longi="";
String lati="";
String loci="";
String selectedProduct="";
int zoom;
    /**
     * Creates new form deliveryAgentHome
     */
    Connection connection;
    public deliveryAgentHome(Connection connection) {

        initComponents();
        this.connection = connection;
        populatedeliveryAgentTable(connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeliveryItems = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cdStatus = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(25, 54, 82));

        tblDeliveryItems.setBackground(new java.awt.Color(25, 54, 82));
        tblDeliveryItems.setForeground(new java.awt.Color(204, 204, 204));
        tblDeliveryItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "order Date", "Items", "Status"
            }
        ));
        tblDeliveryItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeliveryItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDeliveryItems);

        jButton1.setText("view");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Location");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(25, 56, 82));
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Address");

        txtOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIDActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(25, 56, 82));
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Order ID");

        jLabel3.setBackground(new java.awt.Color(25, 56, 82));
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Status");

        cdStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select ...", "Out for Delivery", "Delivered", "Unable to Deliver" }));
        cdStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdStatusActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(jButton1)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addGap(364, 364, 364))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDeliveryItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeliveryItemsMouseClicked
        // TODO add your handling code here

    }//GEN-LAST:event_tblDeliveryItemsMouseClicked

    private void txtOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            PreparedStatement preparedStatement = (PreparedStatement) connection.prepareStatement("update delivery_orders set OrderStatus =? where OrderID = ?");
            preparedStatement.setString(2, selectedProduct);
            preparedStatement.setString(1, cdStatus.getSelectedItem().toString());
            preparedStatement.executeUpdate(); 
            
            PreparedStatement preparedStatement1 = (PreparedStatement) connection.prepareStatement("update shipment_orders set OrderStatus =? where OrderID = ?");
            preparedStatement1.setString(2, selectedProduct);
            preparedStatement1.setString(1, cdStatus.getSelectedItem().toString());
            preparedStatement1.executeUpdate(); 
            
            JOptionPane.showMessageDialog(this, "Updated!!");
            
        }catch(Exception e){
            System.out.println(e);
        }
        txtOrderID.setText(selectedProduct);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        mapMarkerPanel map = new mapMarkerPanel(longi,lati,zoom,selectedProduct);
        this.getParent().add("map area",map);
        CardLayout layout = (CardLayout) this.getParent().getLayout();
        layout.next(this.getParent());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex  = tblDeliveryItems.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a Row to View");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblDeliveryItems.getModel();
         selectedProduct = (String) model.getValueAt(selectedRowIndex,0);
        try{
            PreparedStatement preparedStatement = (PreparedStatement) connection.prepareStatement("select * from user_orders where OrderID = ?");
            preparedStatement.setString(1, selectedProduct);
            ResultSet rs = preparedStatement.executeQuery(); 
            while(rs.next()){
                
                 loci = rs.getString(6);
                 longi = rs.getString(7);
                 lati = rs.getString(8);
                 zoom = Integer.valueOf(rs.getString(9));
                 
                 System.out.println("longi "+longi+" lati "+lati);
            }
        }catch(Exception e){
            System.out.println(e);
        }
        txtOrderID.setText(selectedProduct);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cdStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdStatusActionPerformed
    
    public void populatedeliveryAgentTable(Connection connection){
        DefaultTableModel model = (DefaultTableModel) tblDeliveryItems.getModel();
        model.setRowCount(0);
        try{
            PreparedStatement preparedStatement = (PreparedStatement) connection.prepareStatement("select * from delivery_orders");
            ResultSet rs = preparedStatement.executeQuery(); 
            while(rs.next()){
            Object[] rows = new Object[4];
            rows[0]= rs.getString(1);
            rows[1]=rs.getString(2);
            rows[2]=rs.getString(3);
            rows[3]=rs.getString(4);
            model.addRow(rows);
            }
        }
        catch(SQLException e){System.out.println(e);}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cdStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDeliveryItems;
    private javax.swing.JTextField txtOrderID;
    // End of variables declaration//GEN-END:variables
}
