/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Maps;

import com.kingaspx.util.BrowserUtil;
import com.kingaspx.version.Version;
import com.teamdev.jxbrowser.browser.Browser;
import com.teamdev.jxbrowser.engine.Engine;
import com.teamdev.jxbrowser.engine.EngineOptions;
import static com.teamdev.jxbrowser.engine.RenderingMode.HARDWARE_ACCELERATED;
import com.teamdev.jxbrowser.view.swing.BrowserView;
import java.awt.BorderLayout;


/**
 *
 * @author mahith
 */


public class mapsPanel extends javax.swing.JPanel {
        
    /**
     * Creates new form mapsPanel
     */
    
    Browser browser;
    public mapsPanel() {

        initComponents();
        
        EngineOptions options =
                EngineOptions.newBuilder(HARDWARE_ACCELERATED).licenseKey("1BNDHFSC1G4NNJSWIB7FX6CBOWWCX8MKR14WNT2DH9XV6YW9EOWTXHCOQSIKV88D6J65JS").build();
        Engine engine = Engine.newInstance(options);
        browser = engine.newBrowser();
        BrowserView view = BrowserView.newInstance(browser);
<<<<<<< HEAD
        //browser.navigation().loadUrl("https://www.google.com/maps");
        
        
        String first = "var locations = [\n";
        String second = "['Booking 1', -33.890542, 151.274856, 4],\n['Booking 2', -33.923036, 151.259052, 5]\n";
        String third = "];\n";
        String fourth = "var marker, i;\n\nfor (i = 0; i < locations.length; i++) {  \n  marker = new google.maps.Marker({\n\tposition: new google.maps.LatLng(locations[i][1], locations[i][2]),\n\tmap: map,\n\tlabel: locations[i][0]\n });\n}\n\tbounds.extend(marker.position);";
        
        String setMarkerScript = first+second+third+fourth;
        setMarkers.addActionListener(e -> browser.mainFrame().ifPresent(frame -> frame.executeJavaScript(setMarkerScript)));
        mapArea.add(view);
        
        String rootPath = System.getProperty("user.dir");
        browser.navigation().loadUrl(rootPath+"/simple_map.html/");
        mapArea.add(view);
=======
       
>>>>>>> main
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapArea = new javax.swing.JPanel();
        btnSetLocation = new javax.swing.JButton();
        setMarkers = new javax.swing.JButton();

        mapArea.setLayout(new javax.swing.BoxLayout(mapArea, javax.swing.BoxLayout.LINE_AXIS));

        btnSetLocation.setText("Set Location");
        btnSetLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetLocationActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        setMarkers.setText("Set Location");
=======
        setMarkers.setText("Set Markers");
>>>>>>> main
        setMarkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMarkersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(476, 476, 476)
                .addComponent(btnSetLocation)
<<<<<<< HEAD
                .addGap(61, 61, 61)
                .addComponent(setMarkers)
                .addContainerGap(317, Short.MAX_VALUE))
=======
                .addGap(193, 193, 193)
                .addComponent(setMarkers)
                .addContainerGap(195, Short.MAX_VALUE))
>>>>>>> main
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetLocation)
                    .addComponent(setMarkers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(mapArea, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetLocationActionPerformed
        // TODO add your handling code here:
        if (browser.url()!= null) {
<<<<<<< HEAD
 
            String[] split1= browser.url().split("/place/");
            String[] split2 = split1[1].split("/@");
            String[] placeName = split2[0].split("\\+");
            String[] longLat = split2[1].split(",");
            String place="";
            int size=placeName.length;
            for(int i=0;i<size;i++){
                place+=placeName[i];
=======

//                System.out.println(browser.url());
//                String[] a = browser.url().split("!3d", 0);
//                String[] b = a[1].split("!4d");
//                System.out.println("Lat" + b[0] + "  " + "Lon" + b[1]);
                    
                String[] split1= browser.url().split("/place/");
                String[] split2 = split1[1].split("/@");
                String[] placeName = split2[0].split("\\+");
                String[] longLat = split2[1].split(",");
                String place="";
                
                int size = placeName.length;
                for(int i=0;i<size;i++){
                    place+=placeName[i];
                }
                System.out.println(place);
                System.out.println("long->"+longLat[0]+"lat->"+longLat[1]);
>>>>>>> main
            }
        }
            
    }//GEN-LAST:event_btnSetLocationActionPerformed

    private void setMarkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMarkersActionPerformed
<<<<<<< HEAD
        // TODO add your handling code here:
=======
   
        
// TODO add your handling code here:
>>>>>>> main
    }//GEN-LAST:event_setMarkersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetLocation;
    private javax.swing.JPanel mapArea;
    private javax.swing.JButton setMarkers;
    // End of variables declaration//GEN-END:variables

    
}
