/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface.Maps;

import com.kingaspx.util.BrowserUtil;
import com.kingaspx.version.Version;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.events.ConsoleEvent;
import com.teamdev.jxbrowser.chromium.events.FinishLoadingEvent;
import com.teamdev.jxbrowser.chromium.events.LoadAdapter;
import com.teamdev.jxbrowser.chromium.events.TitleEvent;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import com.teamdev.jxbrowser.engine.Engine;
import com.teamdev.jxbrowser.engine.EngineOptions;
import static com.teamdev.jxbrowser.engine.RenderingMode.HARDWARE_ACCELERATED;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

/**
 *
 * @author mahith
 */
public class testmaps extends javax.swing.JFrame {

    /**
     * Creates new form testmaps
     */
    Browser browser;
    BrowserView view;
    
    public testmaps() {
        initComponents();
        
        Browser browser;
        BrowserView view;
        
        BrowserUtil.setVersion(Version.V6_22);
        
        browser = new Browser();
        view = new BrowserView(browser);
        
        map_panel.add(view,BorderLayout.CENTER);
        
        browser.addTitleListener((TitleEvent evt)->{
            setTitle(evt.getTitle());
            
        });
                
        browser.addConsoleListener((ConsoleEvent evt)->{
            System.out.println("LOG:"+ evt.getMessage());
        });
        
        browser.addLoadListener(new LoadAdapter(){
            public void OnFinishLoadingFrame(FinishLoadingEvent evt){
                evt.getBrowser().setZoomLevel(-2);
            }
        });
        
        browser.loadURL("../../../Google Maps.index.html");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        map_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout map_panelLayout = new javax.swing.GroupLayout(map_panel);
        map_panel.setLayout(map_panelLayout);
        map_panelLayout.setHorizontalGroup(
            map_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        map_panelLayout.setVerticalGroup(
            map_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(map_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(map_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testmaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testmaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testmaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testmaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testmaps().setVisible(true);
            }
        });
        
                        
        
        
        
        
        
//                EngineOptions options =
//                EngineOptions.newBuilder(HARDWARE_ACCELERATED).licenseKey("1BNDHFSC1G4NNJSWIB7FX6CBOWWCX8MKR14WNT2DH9XV6YW9EOWTXHCOQSIKV88D6J65JS").build();
//          Engine engine = Engine.newInstance(options);
//                Browser browser = engine.newBrowser();
//                SwingUtilities.invokeLater(() -> {
//                BrowserView view = BrowserView.newInstance(browser);
//                JTextField addressBar = new JTextField("https://html5test.com");
//                addressBar.addActionListener(e-> browser.navigation ().loadUrl(addressBar.getText()));
//                
//                JFrame frame = new JFrame( "Java Swing Web Browser");
//                frame.addWindowListener (new WindowAdapter() {
//                
//                public void windowClosing (WindowEvent e) {
//                engine.close ();
//                }
//                });
//                
//                frame.add(addressBar, BorderLayout.NORTH);
//                frame.add(view, BorderLayout. CENTER);
//                frame.setDefaultCloseOperation (WindowConstants.DISPOSE_ON_CLOSE);
//                frame.setSize(1280, 900); 
//                frame.setLocationRelativeTo(null);
//                frame.setVisible(true);
//                browser.navigation().loadUrl(addressBar.getText());
//                });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel map_panel;
    // End of variables declaration//GEN-END:variables
}
